# For full config options, check the docs:
#    docs.serverless.com
service: user-service

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  profile: default
  project: user-service
  memorySize: 256 # MB
  timeout: 10 # Seconds
  environment:

package:
  exclude:
    - node_modules/**
    - test/**

functions:
  create-register:
    handler: src/core/user.register
    timeout: 10
    memory: 512
    events:
      - http:
          path: api/register
          method: POST
          cors: true

  get-user-qr-code:
    handler: src/core/user.qrCode
    timeout: 10
    memory: 512
    events:
      - http:
          path: api/qr-code
          method: GET
          cors: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000

plugins:
  - serverless-offline
  - serverless-webpack
